# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 11:46
from __future__ import unicode_literals

import core.models
import core.thumbs.field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.CharField(default=core.models.uuid4_str, max_length=64, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.CharField(default=core.models.uuid4_str, max_length=64, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('leaf', models.BooleanField(default=False)),
                ('glyph', models.CharField(default='xf128@FontAwesome', max_length=256)),
                ('module_xtype', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('groups', models.ManyToManyField(related_name='menus', to='core.Group')),
                ('parent', models.ForeignKey(db_column='parent_uuid', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.Menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebfaceUser',
            fields=[
                ('uuid', models.CharField(default=core.models.uuid4_str, max_length=64, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('image', core.thumbs.field.ImageWithThumbsField(upload_to=core.models.img_path)),
                ('django_user', models.OneToOneField(db_column='django_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='webface_user', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(related_name='users', to='core.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
