# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='flib.proto',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\nflib.proto\"\x08\n\x06\x43ommon')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMON = _descriptor.Descriptor(
  name='Common',
  full_name='flib.proto.Common',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=36,
)

DESCRIPTOR.message_types_by_name['Common'] = _COMMON

Common = _reflection.GeneratedProtocolMessageType('Common', (_message.Message,), dict(
  DESCRIPTOR = _COMMON,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:flib.proto.Common)
  ))
_sym_db.RegisterMessage(Common)


# @@protoc_insertion_point(module_scope)
