# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detectionresult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2
from . import timestamp_pb2
from . import mat_pb2
from . import face_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='detectionresult.proto',
  package='flib.proto',
  serialized_pb=_b('\n\x15\x64\x65tectionresult.proto\x12\nflib.proto\x1a\x0c\x63ommon.proto\x1a\x0ftimestamp.proto\x1a\tmat.proto\x1a\nface.proto\"z\n\x0f\x44\x65tectionResult\x12(\n\ttimestamp\x18\x01 \x02(\x0b\x32\x15.flib.proto.Timestamp\x12\x1c\n\x03mat\x18\x02 \x01(\x0b\x32\x0f.flib.proto.Mat\x12\x1f\n\x05\x66\x61\x63\x65s\x18\x03 \x03(\x0b\x32\x10.flib.proto.Face')
  ,
  dependencies=[common_pb2.DESCRIPTOR,timestamp_pb2.DESCRIPTOR,mat_pb2.DESCRIPTOR,face_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETECTIONRESULT = _descriptor.Descriptor(
  name='DetectionResult',
  full_name='flib.proto.DetectionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='flib.proto.DetectionResult.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mat', full_name='flib.proto.DetectionResult.mat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='faces', full_name='flib.proto.DetectionResult.faces', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=213,
)

_DETECTIONRESULT.fields_by_name['timestamp'].message_type = timestamp_pb2._TIMESTAMP
_DETECTIONRESULT.fields_by_name['mat'].message_type = mat_pb2._MAT
_DETECTIONRESULT.fields_by_name['faces'].message_type = face_pb2._FACE
DESCRIPTOR.message_types_by_name['DetectionResult'] = _DETECTIONRESULT

DetectionResult = _reflection.GeneratedProtocolMessageType('DetectionResult', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONRESULT,
  __module__ = 'detectionresult_pb2'
  # @@protoc_insertion_point(class_scope:flib.proto.DetectionResult)
  ))
_sym_db.RegisterMessage(DetectionResult)


# @@protoc_insertion_point(module_scope)
