# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: landmark.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2
from . import point2i_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='landmark.proto',
  package='flib.proto',
  serialized_pb=_b('\n\x0elandmark.proto\x12\nflib.proto\x1a\x0c\x63ommon.proto\x1a\rpoint2i.proto\";\n\x08Landmark\x12\x0b\n\x03idx\x18\x01 \x02(\x05\x12\"\n\x05point\x18\x02 \x02(\x0b\x32\x13.flib.proto.Point2i')
  ,
  dependencies=[common_pb2.DESCRIPTOR,point2i_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LANDMARK = _descriptor.Descriptor(
  name='Landmark',
  full_name='flib.proto.Landmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='flib.proto.Landmark.idx', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='flib.proto.Landmark.point', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=118,
)

_LANDMARK.fields_by_name['point'].message_type = point2i_pb2._POINT2I
DESCRIPTOR.message_types_by_name['Landmark'] = _LANDMARK

Landmark = _reflection.GeneratedProtocolMessageType('Landmark', (_message.Message,), dict(
  DESCRIPTOR = _LANDMARK,
  __module__ = 'landmark_pb2'
  # @@protoc_insertion_point(class_scope:flib.proto.Landmark)
  ))
_sym_db.RegisterMessage(Landmark)


# @@protoc_insertion_point(module_scope)
