# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2
from . import pair32i_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mat.proto',
  package='flib.proto',
  serialized_pb=_b('\n\tmat.proto\x12\nflib.proto\x1a\x0c\x63ommon.proto\x1a\rpair32i.proto\"\x9b\x01\n\x03Mat\x12\r\n\x05\x64\x65pth\x18\x01 \x02(\x05\x12\x10\n\x08\x63hannels\x18\x02 \x02(\x05\x12\x0c\n\x04rows\x18\x03 \x02(\x05\x12\x0c\n\x04\x63ols\x18\x04 \x02(\x05\x12\x0c\n\x04step\x18\x05 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x06 \x02(\x0c\x12\x16\n\x07\x65ncoded\x18\x07 \x01(\x08:\x05\x66\x61lse\x12#\n\x06params\x18\x08 \x03(\x0b\x32\x13.flib.proto.Pair32i')
  ,
  dependencies=[common_pb2.DESCRIPTOR,pair32i_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAT = _descriptor.Descriptor(
  name='Mat',
  full_name='flib.proto.Mat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth', full_name='flib.proto.Mat.depth', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='flib.proto.Mat.channels', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='flib.proto.Mat.rows', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cols', full_name='flib.proto.Mat.cols', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='flib.proto.Mat.step', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='flib.proto.Mat.data', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoded', full_name='flib.proto.Mat.encoded', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='flib.proto.Mat.params', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=210,
)

_MAT.fields_by_name['params'].message_type = pair32i_pb2._PAIR32I
DESCRIPTOR.message_types_by_name['Mat'] = _MAT

Mat = _reflection.GeneratedProtocolMessageType('Mat', (_message.Message,), dict(
  DESCRIPTOR = _MAT,
  __module__ = 'mat_pb2'
  # @@protoc_insertion_point(class_scope:flib.proto.Mat)
  ))
_sym_db.RegisterMessage(Mat)


# @@protoc_insertion_point(module_scope)
