# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pair32i.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pair32i.proto',
  package='flib.proto',
  serialized_pb=_b('\n\rpair32i.proto\x12\nflib.proto\x1a\x0c\x63ommon.proto\"%\n\x07Pair32i\x12\x0b\n\x03key\x18\x01 \x02(\x05\x12\r\n\x05value\x18\x02 \x02(\x05')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PAIR32I = _descriptor.Descriptor(
  name='Pair32i',
  full_name='flib.proto.Pair32i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='flib.proto.Pair32i.key', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='flib.proto.Pair32i.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['Pair32i'] = _PAIR32I

Pair32i = _reflection.GeneratedProtocolMessageType('Pair32i', (_message.Message,), dict(
  DESCRIPTOR = _PAIR32I,
  __module__ = 'pair32i_pb2'
  # @@protoc_insertion_point(class_scope:flib.proto.Pair32i)
  ))
_sym_db.RegisterMessage(Pair32i)


# @@protoc_insertion_point(module_scope)
