# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point2i.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='point2i.proto',
  package='flib.proto',
  serialized_pb=_b('\n\rpoint2i.proto\x12\nflib.proto\x1a\x0c\x63ommon.proto\"\x1f\n\x07Point2i\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POINT2I = _descriptor.Descriptor(
  name='Point2i',
  full_name='flib.proto.Point2i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='flib.proto.Point2i.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='flib.proto.Point2i.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['Point2i'] = _POINT2I

Point2i = _reflection.GeneratedProtocolMessageType('Point2i', (_message.Message,), dict(
  DESCRIPTOR = _POINT2I,
  __module__ = 'point2i_pb2'
  # @@protoc_insertion_point(class_scope:flib.proto.Point2i)
  ))
_sym_db.RegisterMessage(Point2i)


# @@protoc_insertion_point(module_scope)
